import express from "express";
import { protect } from "../middleware/authMiddleware.js";
import { applyJob, getCompanyApplications, getUserApplications } from "../controllers/applicationController.js";
import { authorizeRoles } from "../middleware/roleMiddleware.js";
import { ROLES } from "../utils/roles.js";
const router = express.Router();
router.post("/",protect,authorizeRoles(ROLES.USER),applyJob);
router.get("/user",protect,authorizeRoles(ROLES.USER),getUserApplications);
router.get("/company",protect,authorizeRoles(ROLES.COMPANY),getCompanyApplications);
export default router;